name: llm-verifier
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py310h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py310haa95532_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - idna=3.11=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h5da7b33_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgomp=15.2.0=h1383e82_7
  - libjpeg-turbo=3.1.1=h02ab6af_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libtiff=4.7.0=hfc51747_1
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.0.18=h543e019_0
  - pillow=11.3.0=py310hb3a2f59_3
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h3c9f919_1
  - pycparser=2.23=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - python_abi=3.10=2_cp310
  - pytorch=2.3.0=py3.10_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h827c3e9_0
  - requests=2.32.5=py310haa95532_1
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - typing_extensions=4.15.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py310haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.48.2
      - bleach==6.3.0
      - braceexpand==0.1.7
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - grpcio==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - intel-openmp==2021.4.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - libauc==1.4.0
      - littleutils==0.2.4
      - markdown==3.10
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - mkl==2021.4.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - ogb==1.3.6
      - opencv-python==4.12.0.88
      - outdated==0.2.2
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - peft==0.18.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - tbb==2021.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch-geometric==2.7.0
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webdataset==1.0.2
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\joyve\anaconda3\envs\llm-verifier
